import "../styles/globals.css";
import localFont from "next/font/local";
import Providers, { Print } from "@/providers";

import Link from "next/link";
const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={pretendard.className}>
        <Providers>
          <div className="h-full">{children}</div>
          <div className="__portal" />
        </Providers>
      </body>
    </html>
  );
}
